on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connected to EC2!"
            sudo apt update -y
            sudo rm -rf frontend
            echo "Removed frontend folder"
            git clone https://github.com/muhammadwamiq/frontend.git
            echo "Cloning to GITHUB done"
            ls
            echo "listing files of current directiory"
            cd frontend
            echo "Moved inside project folder"
            sudo npm install 
            echo "dependencies installed" 
            sudo npm run build
            echo "running build"
            cd /var/www/html/frontend
            cp -r /home/ubuntu/frontend/build/* .
            sudo nginx -t 
            echo "testing nginx"
            sudo systemctl reload nginx 
            echo "nginx reloaded"
